version: '3'

services:

  legacy-app:
    restart: always
    image: localhost:5000/legacy-java-webapp:latest
    ports:
      - 8081:8080
    tmpfs:
      - /usr/local/tomcat/conf/Catalina
      - /usr/local/tomcat/work
      - /usr/local/tomcat/temp
      - /usr/local/tomcat/logs
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  modern-app:
    restart: always
    image: localhost:5000/modern-java-webapp:latest
    ports:
      - 8082:8080
    tmpfs:
      - /tmp
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ui:
    restart: always
    image: portainer/portainer
    command: --no-auth --templates http://ui-templates/templates.json
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /data:rw,exec

  ui-templates:
    restart: always
    image: portainer/templates
    