version: '3'

services:

  legacy-app:
    restart: always
    image: ${docker.registry}/legacy-java-webapp:latest
    ports:
      - "${TOMCAT_PORT:-8081}:8080"
    tmpfs:
      - /usr/local/tomcat/conf/Catalina
      - /usr/local/tomcat/work
      - /usr/local/tomcat/temp
      - /usr/local/tomcat/logs
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  modern-app:
    restart: always
    image: ${docker.registry}/modern-java-webapp:latest
    ports:
      - "${SERVER_PORT:-8082}:8080"
    tmpfs:
      - /tmp
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ui:
    restart: always
    image: portainer/portainer
    command: --templates http://ui-templates/templates.json
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ui-data:/data

  ui-templates:
    restart: always
    image: portainer/templates

volumes:
  ui-data:
