version: '3'

services:

  legacy-java-webapp:
    restart: always
    image: ${docker.registry}/legacy-java-webapp:${project.version}
    ports:
      - "${TOMCAT_PORT:-8081}:8080"
    tmpfs:
      - /usr/local/tomcat/conf/Catalina
      - /usr/local/tomcat/work
      - /usr/local/tomcat/temp
      - /usr/local/tomcat/logs
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  modern-java-webapp:
    restart: always
    image: ${docker.registry}/modern-java-webapp:${project.version}
    ports:
      - "${SERVER_PORT:-8082}:8080"
    tmpfs:
      - /tmp
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  management-ui:
    restart: always
    image: portainer/portainer
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ui-data:/data

volumes:
  ui-data: