version: '3'

services:

  legacy-java-webapp:
    restart: always
    build:
      context: ./legacy-java-webapp
      args:
        HOST_UID: "${HOST_UID}"
        HOST_GID: "${HOST_GID}"
    ports:
      - "${TOMCAT_PORT:-8081}:8080"
    tmpfs:
      - /usr/local/tomcat/conf/Catalina
      - /usr/local/tomcat/work
      - /usr/local/tomcat/temp
      - /usr/local/tomcat/logs
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev
    env_file:
      - env.d/legacy.env

  modern-java-webapp:
    restart: always
    build:
      context: ./modern-java-webapp
      args:
        HOST_UID: "${HOST_UID}"
        HOST_GID: "${HOST_GID}"
    ports:
      - "${SERVER_PORT:-8082}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev
    env_file:
      - env.d/new.env

  management-ui:
    restart: always
    image: portainer/portainer
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./var/portainer:/data
